---

- block:
    - name: compute package list
      set_fact:
        expected_packages: "{{ \
                 (packages['common'] | d([])) \
                 + (packages[hosttype] | d([])) \
                 + (vars['packages_' + ansible_distribution_major_version]['common'] | d([])) \
                 + (vars['packages_' + ansible_distribution_major_version][hosttype] | d([])) \
                 + (vars['packages_' + ansible_distribution_version]['common'] | d([])) \
                 + (vars['packages_' + ansible_distribution_version][hosttype] | d([])) \
              }}"

    - name: update catalog
      shell: "pkg update -q"
      changed_when: false

    - name: "pkg install (with {{ hosttype }} packages)"
      pkgng:
        name: "{{ expected_packages }}"
        state: latest

  when: ansible_system == 'FreeBSD'
