---

- block:
    - name: get CPU model
      command: sysctl hw.model
      changed_when: false
      register: t_cpu_model

    - name: disable unwanted temperature modules
      include_tasks: kernel_module.yml
      vars:
        module_name: "{{ item.module }}"
        module_status: disable
      loop: "{{ temperature_modules }}"
      when: t_cpu_model.stdout is not search(item.cpu)

    - name: enable expected temperature modules
      include_tasks: kernel_module.yml
      vars:
        module_name: "{{ item.module }}"
        module_status: enable
      loop: "{{ temperature_modules }}"
      when: t_cpu_model.stdout is search(item.cpu)

  when: ansible_system == 'FreeBSD'
